# Site Settings
locale                   : "en-US"
rtl                      : false  # false برای زبان‌های راست به چپ مثل فارسی، true 
title                    : "AryanBj Blog"
title_separator          : "-"
subtitle                 : "A journey in coding and personal growth"  # تگ‌لاین سایت که زیر عنوان سایت نمایش داده می‌شود
name                     : "Aryan Bajelani"
description              : "A blog dedicated to sharing my programming learning journey, with a focus on Python and personal skill development. Here, I document my experiences and small projects to serve as a portfolio and a resource for learning and growth in the world of coding."
url                      : "https://aryanbajelani.com"  # آدرس سایت 
baseurl                  : ""  # زیرشاخه سایت، خالی بگذارید اگر مستقیم در دامنه اصلی است
repository               : "AryanBj/minimal-mistakes"  # نام کاربری و نام مخزن GitHub
teaser                   : "/assets/images/500x300.png"  # آدرس تصویر fallback teaser
logo                     : "/assets/images/logo.png"  # آدرس تصویر لوگو برای نمایش در سربرگ سایت
masthead_title           : "AryanBj Blog"  # عنوان سایت که در سربرگ نمایش داده می‌شود
breadcrumbs              : true  # فعال‌سازی مسیرهای ناوبری
words_per_minute         : 200
enable_copy_code_button  : true  # فعال‌سازی دکمه کپی کد
copyright                : "AryanBj Blog"  # نام کپی رایت، پیش‌فرض سایت
copyright_url            : "https://aryanbajelani.com"  # آدرس کپی رایت، پیش‌فرض سایت

comments:
  provider               : "disqus"
  disqus:
    shortname            : "aryanbajelani"  # نام کوتاه Disqus برای تنظیمات نظرات

reCaptcha:
  siteKey                : "YOUR_SITE_KEY"
  secret                 : "YOUR_SECRET_KEY"

atom_feed:
  path                   : "feed.xml"
  hide                   : false

search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true

google:
  search_engine_id       : "YOUR_SEARCH_ENGINE_ID"
  instant_search         : true

# SEO Related
google_site_verification : "YOUR_GOOGLE_SITE_VERIFICATION_CODE"
bing_site_verification   : "YOUR_BING_SITE_VERIFICATION_CODE"
naver_site_verification  : "YOUR_NAVER_SITE_VERIFICATION_CODE"
yandex_site_verification : "YOUR_YANDEX_SITE_VERIFICATION_CODE"
baidu_site_verification  : "YOUR_BAIDU_SITE_VERIFICATION_CODE"

# Social Sharing
twitter:
  username               : "your_twitter_username"
facebook:
  username               : "your_facebook_username"
  app_id                 : "your_facebook_app_id"
og_image                 : "/assets/images/social-share.png"  # تصویر پیش‌فرض برای Open Graph/Twitter

social:
  type                   : "Person"
  name                   : "Aryan Bajelani"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:aryan_bj@yahoo.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aryanbajelani.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/your_twitter_username"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/your_facebook_username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your_github_username"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/your_instagram_username"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "YOUR_GOOGLE_ANALYTICS_TRACKING_ID"
    anonymize_ip         : true

# Site Author
author:
  name             : "Aryan Bajelani"
  avatar           : "/assets/images/bio-photo.jpg"  # آدرس تصویر آواتار
  bio              : "I am Aryan, a Python programmer."
  location         : "Iran"
  email            : "aryan_bj@yahoo.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:aryan_bj@yahoo.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aryanbajelani.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/your_twitter_username"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/your_facebook_username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your_github_username"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/your_instagram_username"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/your_twitter_username"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/your_facebook_username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your_github_username"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/your_gitlab_username"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/your_bitbucket_username"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/your_instagram_username"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "Asia/Tehran"  # تنظیم منطقه زمانی

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
