# تنظیمات پایه
title: "وبلاگ شخصی من"
description: "اینجا نوشته‌ها و پروژه‌های من را خواهید یافت!"
author:
  name: "Aryan"
  email: "aryan_bj@yahoo.com" , "aryanbj2@gmail.com

# تنظیمات URL
baseurl: "" # وقتی روی دامنه‌ی اصلی هست، باید خالی باشه
url: "https://aryanbj.github.io" # آدرس سایت شما

# تنظیمات تم
theme: jekyll-theme-minimal # می‌توانید با دیگر تم‌ها نیز امتحان کنید

# لینک شبکه‌های اجتماعی
social_links:
  - name: GitHub
    url: "https://github.com/aryanbj"
    icon: "fab fa-github" 
  - name: LinkedIn
    url: "https://www.linkedin.com/in/aryan-bajelani-3843019a/"
    icon: "fab fa-linkedin" 
  - name: Twitter
    url: "https://twitter.com/aryan_bj"
    icon: "fab fa-twitter" 
  - name: Instagram
    url: "https://instagram.com/aryan__bj"
    icon: "fab fa-instagram"

# پیکربندی صفحات
permalink: /:categories/:title/
paginate: 5 # تعداد پست‌ها در هر صفحه
paginate_path: "/page:num/"

# تنظیمات اضافی و پلاگین‌ها
plugins:
  - jekyll-feed # برای فید آر اس اس
  - jekyll-seo-tag # برای بهینه‌سازی SEO
  - jekyll-sitemap # ایجاد نقشه سایت
